env:
  browser: true
  commonjs: false
  es6: true
  node: true
  mocha: true
extends: ['react-app', 'plugin:prettier:recommended']
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  globalThis: readonly
  expect: readonly
  beforeAll: readonly
  afterAll: readonly
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
